apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: kube-scraper
  labels:
    run: backend
spec:
  ports:
  - port: 80
    targetPort: 8787
    protocol: TCP
  selector:
    run: backend